server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com     #  web 访问地址：http://eureka7002.com:7002/
  client:
    register-with-eureka: false  #false表示不向注册中心注册自己。
    fetch-registry: false        #false 表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检测服务
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/    #这是集群状态下，这里得指向另外一台服务主机，相互守望，守望7002端口的eureka

#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/